### PR TITLE
placker.com itegration

### PR DESCRIPTION
**Pull request by amadeuszprus**

### CODE REVIEW

**Comment by milosfromcake** [comment]
Hello, @mkurzeja.

Thanks for trying to extend the list of integrations of our project.

I have forwarded the builds for testing to our QA team. If no defects are discovered, your code will be merged very soon and available to users from the first next version of the Clockify Extension.

All the best, my friend.

**Comment by mkurzeja** [comment]
@milosfromcake thanks! 

Let me know if you need any help.

**Comment by mkurzeja** [comment]
Hi @milosfromcake 

Any updates on this? Sorry for pinging, but we have some customers of both Clockify and placker.com that requested this and are asking us when they can expect it to be live.

**Comment by milosfromcake** [comment]
Hey @mkurzeja,

Your code (Placker integration) has been live for 2 days on the latest version of the Chrome extension. As soon as the final version of the extension is approved by the Firefox reviewers (probably in a few days - rough estimation), your code will be live there as well and I'll merge the changes.

Thank you for waiting and for your patience. :))

**Comment by milosfromcake** [comment]
Placker integration is now available on Firefox too. I am merging.

**Pull request merged**
