### PR TITLE
Fix project name on Todoist Integration

### LINKED ISSUE #240: Todoist integration includes section with project name
The Todoist integration is grabbing the section as part of the project name on the filter view. 

Todoist
CleanShot 2023-05-13 at 16 11 43

Clockify
CleanShot 2023-05-13 at 16 12 52

This is messing with my project matching. This shouldn't be a hard thing to fix.

### PR DESCRIPTION
**Pull request by cvbrian**
Fixes #240 

Remove section from project name on Todoist and also fix a description error I ran across on the same section. This was on the filters page. 
Let me know if this doesn't work.

### CODE REVIEW

**Comment by stefancoing** [comment]
Thank you for the contribution, will look into this fix as soon as possible

**Comment by cvbrian** [comment]
I found another bug in the Todoist task modal. I've got a fix for it as well. It is similar to this one. Do you want me to add that to this pull request?

**Comment by nikocevicstefan** [comment]
@cvbrian Hi @cvbrian , sure, feel free to add it.

**Comment by stefancoing** [comment]
Hi @cvbrian, sure, feel free to to add it.

**Comment by cvbrian** [comment]
Ok, I've added it.

**Pull request merged**
