### PR TITLE
Plane integration

### PR DESCRIPTION
**Pull request by mmospanenko**
image
Adds Issue details Clockify button. Grabs Description, Project, Task values.

### CODE REVIEW

**Comment by milosfromcoing** [comment]
Hi @mmospanenko, thank you for pull request you've created. We will accept changes you've made.

**Comment by mabdullahabid** [comment]
Can we get this merged please? What's the process of building a PR from scratch and deploying it somewhere for use/testing?

**Comment by mmospanenko** [comment]
@mabdullahabid thank you for interest to PR)

you can install it manually
1. clone (our fork)/checkout on this branch
2. `npm install`
3. `npm run compile.dev.chrome`
4. In Chrome Extensions, turn on Developer mode and Load Unpacked build folder

**Comment by milosfromcoing** [comment]
Hi @mmospanenko ,

We apologize for keeping you waiting for feedback. As things stand, the Plane web application frequently changes its page structure (its HTML), minimally but enough to break the selectors used by the integration, making the integration broken. The code you committed broke shortly after, and despite us fixing it multiple times, the code continued to break for periods of several days.

For this reason, unfortunately, we decided not to accept the changes you made and not to support integration for Plane application after all, and we apologize for initially saying that the changes would be accepted and integration supported.

We hope you will continue to contribute to our project, and for that we are grateful.

**Comment by mabdullahabid** [comment]
How would I make this work on versions 0.20+?

**Comment by mmospanenko** [comment]
we will test and update soon

**Comment by mmospanenko** [comment]
works correctly with 22-dev. All these versions didn't broke integration, so sentence "the Plane web application frequently changes its page" not really true :)

**Comment by mabdullahabid** [comment]
It doesn't work for me. I'll try again and share results.

**Comment by mabdullahabid** [comment]
@milosfromcake given the recent response from @mmospanenko, do you think we can reconsider including this as part of the core browser-extension code?

**Comment by milosfromcake** [comment]
Hello guys. Our QA team can test your code one more time. Based on the new testing, we may reconsider including your code in our repository.

**Comment by milosfromcake** [comment]
After our QA team has tested your code again, I can give you the following update:

1) when the task is opened through "workspace -> views", the "All issues" string is picked up as a project, this is definitely unexpected behavior 
2) when the task sidebar is expanded, the timer is not displayed
3) this is not crucial but stands out from other integrations is the position of the timer; usually a small button is placed after the other action icons on the page/row/sidebar/modal, which in this case would be the top of the sidebar

We can wait for a fix, but I believe that it will not be easy to make, considering that it is difficult to make reliable selectors that do not contain styling classes.

**Comment by mmospanenko** [comment]
Ok, thank you for so detailed feedback, sure, all extensions should work consistently, and we will prepare fixes in the near future (I believe it is possible to implement, even if we will write some ugly css selectors :))

**Pull request closed without merging**
