### PR TITLE
Automatic assignment to tasks

### PR DESCRIPTION
**Pull request by dpoetzsch**
Hi,

in our company we have an extensive use of gitlab issues. For our customers, we need to be able to easily calculate the number of hours spent on each issue.

Thus, we thought it would be best, if each issue in a project A matches a clockify task ind project A.

For now, the clockify browser plugin already matches the projects. We extended it, so that time is always tracked on a matching task.

Maybe this is something the community is interested in as well, so we created this PR to share it. If this does not find the way into master it is fine as well, we'd just use our own fork then.

PS: Thanks for creating such awesome software btw, it was really fun to extend.

PPS: We even did some more extensions (tag transfer from gitlab, billable settings), if this would be something you're interested in I'm happy to create another PR or extend this one.

### CODE REVIEW

**Comment by aleksandar-olic** [comment]
Hi David,

Wow, this is awesome! Thanks for the PR, we'd love to add it.

I've tested it a bit and there are a couple of issues that need to be fixed before we can merge:

- Bug: If there's no project in Gitlab with a mathcing name in Clockify, the timer won't start (it should start with only description)
- Bug: If you are a regular user and don't have permission to create tasks, the timer won't start (it should start with description + project if possible)
- Nice-to-have feature: The extension creates a task if the user has the permission, which is great. It'd be awesome if it can create a project too (if user has adequate permission), plus the option to turn off auto-create in Settings (for both projects, tasks, and tags).
-Nice-to-have feature: Adding tags would also be very nice, so feel free to add it here.

Hope this helps. Again, thanks for the PR, it's awesome!

**Comment by dpoetzsch** [comment]
Thanks for the extensive review.

I fixed both bugs and added the nice-to-have features project creation and tags. The tags are implemented for gitlab only, the project creation is enabled for all integrations that set a project name.

I also added a setting to enable/disable creation of projects/tasks/tags. So far this is only a *single* setting for all of them, as I thought it's probably better to not make this too complicated. This could obviously be changed.

However, I was not able to test the updated settings page, as it does not render in dev mode in chrome (also not in firefox as it seems). I did test the setting by manually changing the local storage, which works fine.

**Comment by aleksandar-olic** [comment]
Awesome! I've tried to add the new code to my local version and for some reason the Settings page is blank. I've tried to compile from your repo but got the same issue. I've also tried in another version, and there it can open the Settings and I see the option, but the Start button won't work (neither in Gitlab nor in other apps, like Asana or Trello). That's really strange.

Let me know if you manage to find what could be the issue. In the meantime, I'll invite someone from my team to take a look.

**Comment by aleksandar-olic** [comment]
There was an issue with Settings page, but we've fixed it and merged it. Everything seems to work fine (yay!), except the createSmallButton. All tiemrs in integrations that use the small button can't be started at all.

**Comment by dpoetzsch** [comment]
Oh that might be my bad, :-/

I'll open a PR to fix that

**Pull request merged**
